// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkbdolijonlubpgidozk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrYmRvbGlqb25sdWJwZ2lkb3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNDY4MDgsImV4cCI6MjA1MjcyMjgwOH0.xT39JTIect8VmsYF2kccAyyrXz5AHNI-aq6Cr4nt1j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);